name: Server Bug Report
description: Report Server Bugs/Crashes here
title: "[Bug]: "
labels: ["server"]
body:
  - type: markdown
    attributes:
      value: |-
        ## Have you searched for similar [issues](https://github.com/iamtokimi/homestead/issues?q=is%3Aissue%20state%3Aopen%20label%3Aserver)?
        ### Insufficiently described issues will be closed, so please provide as much information as possible

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: A series of steps to reproduce the issue
      value: |-
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: result
    attributes:
      label: Actual result
      description: What happened
      placeholder: Include screenshots/videos if needed
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected result
      description: What should've happened
      placeholder: Include screenshots/videos if needed
    validations:
      required: true

  - type: markdown
    attributes:
      value: |-
        ## Log Reporting
        ### If you are reporting a bug, please provide your server logs for the session that the bug happened on.
        ### If you are reporting a crash, please provide the crash logs __**as well.**__
        ### You can find a helpful tutorial [here](https://youtu.be/7741eM273fs).

  - type: textarea
    id: crash_logs
    attributes:
      label: Server Logs
      description: Report Logs here.
      placeholder: https://mclo.gs/...
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: Please include information on your system, such as OS, Hoster Used, Modpack Version, and other additional specs
      value: |-
        OS: [e.g. Windows 11, macOS Sequoia 15, Linux Ubuntu 22.04]
        Server Hoster: [e.g. Docker, Modrinth Servers, Bisect Hosting]
        Modpack Version: [e.g. 1.0.0]
        Additional Specs: [CPU, GPU, general hardware information]
    validations:
      required: true

  - type: textarea
    id: misc
    attributes:
      label: Miscellaneous information
      description: Any additional information, related issues, configuration or data that might be necessary to reproduce the issue
    validations:
      required: false
