name: Feature Request
description: Request Features Here
title: "[Feature Request]: "
labels: [ "feature request" ]
body:
  - type: markdown
    attributes:
      value: |-
        ## Have you searched for similar [feature requests](https://github.com/iamtokimi/homestead/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22feature%20request%22)?
        ### Insufficiently described requests will be closed, so please provide as much information as possible

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |-
        A clear and concise description of what the feature is. What does it do, and why does it fit Homestead?
        If you are submitting mods for review, please also send their Modrinth links below. 
    validations:
      required: true

  - type: markdown
    attributes:
      value: |-
        ## If you are submitting a mod for review, please verify that it has **an existing page on Modrinth.** If it is not on Modrinth, we cannot add it to the pack!
        ### Please also test this mod with all other mods in the pack and confirm that there are **no compatibility issues whatsoever.**
        ### *Remember: Homestead is built on Minecraft Java 1.20.1, with Fabric 0.16.14!*

  - type: checkboxes
    id: verify
    attributes:
      label: Confirmation
      description:
      options:
        - label: I confirm that this mod has an existing page on Modrinth.
          required: false
        - label: I confirm that I have thoroughly tested this mod with Homestead and have found no compatibility issues.
          required: false

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: In case we decide to follow up with you privately on this feature request, please send your discord username (or another preferred manner of communication).
    validations:
      required: true

  - type: textarea
    id: misc
    attributes:
      label: Miscellaneous information
      description: Any additional information or context that you would like to share?
    validations:
      required: false
