name: Bug Report
description: Report Bugs/Crashes here
body:
  - type: markdown
    attributes:
      value: |-
        Have you searched for similar [issues](https://github.com/iamtokimi/homestead/issues)?
        Insufficiently described issues will be closed, so please provide as much information as possible

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: A series of steps to reproduce the issue
      value: |-
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: result
    attributes:
      label: Actual result
      description: What happened
      placeholder: Include screenshots if needed
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expected result
      description: What should've happened
      placeholder: Include screenshots if needed
    validations:
      required: true

  - type: markdown
    attributes:
      value: |-
        If you are reporting a crash, **please include your crash log!** 
        You can find a helpful tutorial [here](https://youtu.be/7741eM273fs).

  - type: textarea
    id: crash_logs
    attributes:
      label: Crash Logs
      description: Report Server/Crash Logs here.
      placeholder: https://mclo.gs/...
    validations:
      required: false

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: Please include information on your system, such as OS, Launcher Used, Modpack Version, and other Additional Computer Specs
      value: |-
        OS: [e.g. Windows 11, macOS Sequoia 15, Linux Ubuntu 22.04]
        Launcher: [e.g. Modrinth, Prism]
        Modpack Version: [e.g. 1.0.0]
        Additional Computer Specs: [CPU, GPU, general hardware information]

  - type: textarea
    id: misc
    attributes:
      label: Miscellaneous information
      description: Any additional information, related issues, configuration or data that might be necessary to reproduce the issue
